export class WebinarsService {
  private webinars = [
    {
      id: 1,
      "title": ' Dont Make This 1 change Order Mistake, or it Will Cost You Big Time.',
      "description": 'Learn about the mistakes people commit with change orders which cost them big time in this webinar hosted my Ariela Wagner, President, SunRay Construction Solutions and Alex Barthet Esq. Board Certified Lawyer and founder of The Lien zone.',
      "waiting_period": "14 Days",
      "webinar_day": new Date(15, 1, 2017),
      "start_time": '9:00 am',
      "end_time": '11:00 am',
      "status": "paid",
      "duration": "00:20",
      "webinar_image": "/assets/frontend/webinars/5th-webinar.jpg",
      "president_name": 'Ariela Wagner',
      "president_image": "/assets/frontend/webinars/ariela.png",
      "principal_name": 'Alex Barthet',
      "principal_image": "/assets/frontend/webinars/barthet.png",
      "video_url": "https://www.youtube.com/embed/PqxThzHfAXQ"
    },
    {
      id: 2,
      "title": 'Wait, What? I Only Have 40 Days to Send my NTO?',
      "description": 'Learn about the mistakes people commit with change orders which cost them big time in this webinar hosted my Ariela Wagner, President, SunRay Construction Solutions and Alex Barthet Esq. Board Certified Lawyer and founder of The Lien zone.',
      "waiting_period": "In June",
      "webinar_day": new Date(15, 6, 2018),
      "start_time": '9:00 am',
      "end_time": '11:00 am',
      "status": "paid",
      "duration": "00:20",
      "webinar_image": "/assets/frontend/webinars/6th-webinar.jpg",
      "president_name": 'Ariela Wagner',
      "president_image": "/assets/frontend/webinars/ariela.png",
      "principal_name": 'Alex Barthet',
      "principal_image": "/assets/frontend/webinars/barthet.png",
      "video_url": "https://www.youtube.com/embed/PqxThzHfAXQ"
    },
    {
      id: 3,
      "title": 'My Lien was Bonded Off. Now What?',
      "description": 'Learn about the mistakes people commit with change orders which cost them big time in this webinar hosted my Ariela Wagner, President, SunRay Construction Solutions and Alex Barthet Esq. Board Certified Lawyer and founder of The Lien zone.',
      "waiting_period": "In July",
      "webinar_day": new Date(15, 7, 2018),
      "start_time": '9:00 am',
      "end_time": '11:00 am',
      "status": "paid",
      "duration": "00:20",
      "webinar_image": "/assets/frontend/webinars/7th-webinar.jpg",
      "president_name": 'Ariela Wagner',
      "president_image": "/assets/frontend/webinars/ariela.png",
      "principal_name": 'Alex Barthet',
      "principal_image": "/assets/frontend/webinars/barthet.png",
      "video_url": "https://www.youtube.com/embed/PqxThzHfAXQ"
    },
    {
      id: 4,
      "title": 'Pay-When-Paid Sucks, So Do This to Get Paid Anyways',
      "description": 'Learn about the mistakes people commit with change orders which cost them big time in this webinar hosted my Ariela Wagner, President, SunRay Construction Solutions and Alex Barthet Esq. Board Certified Lawyer and founder of The Lien zone.',
      "waiting_period": "In August",
      "webinar_day": new Date(15, 8, 2018),
      "start_time": '9:00 am',
      "end_time": '11:00 am',
      "status": "paid",
      "duration": "00:20",
      "webinar_image": "/assets/frontend/webinars/4th-webinar.jpg",
      "president_name": 'Ariela Wagner',
      "president_image": "/assets/frontend/webinars/ariela.png",
      "principal_name": 'Alex Barthet',
      "principal_image": "/assets/frontend/webinars/barthet.png",
      "video_url": "https://www.youtube.com/embed/PqxThzHfAXQ"
    },
    {
      id: 5,
      "title": '3 Lien Release Tricks You Need to Know',
      "description": 'Learn about the mistakes people commit with change orders which cost them big time in this webinar hosted my Ariela Wagner, President, SunRay Construction Solutions and Alex Barthet Esq. Board Certified Lawyer and founder of The Lien zone.',
      "waiting_period": "In September",
      "webinar_day": new Date(15, 9, 2018),
      "start_time": '9:00 am',
      "end_time": '11:00 am',
      "status": "paid",
      "duration": "00:20",
      "webinar_image": "/assets/frontend/webinars/9th-webinar.jpg",
      "president_name": 'Ariela Wagner',
      "president_image": "/assets/frontend/webinars/ariela.png",
      "principal_name": 'Alex Barthet',
      "principal_image": "/assets/frontend/webinars/barthet.png",
      "video_url": "https://www.youtube.com/embed/PqxThzHfAXQ"
    },
    {
      id: 6,
      "title": 'Can I Lien Homestead Property(& Other Lien Questions Answered)?',
      "description": 'Learn about the mistakes people commit with change orders which cost them big time in this webinar hosted my Ariela Wagner, President, SunRay Construction Solutions and Alex Barthet Esq. Board Certified Lawyer and founder of The Lien zone.',
      "waiting_period": "In October",
      "webinar_day": new Date(15, 10, 2018),
      "start_time": '9:00 am',
      "end_time": '11:00 am',
      "status": "paid",
      "duration": "00:20",
      "webinar_image": "/assets/frontend/webinars/3rd-webinar.jpg",
      "president_name": 'Ariela Wagner',
      "president_image": "/assets/frontend/webinars/ariela.png",
      "principal_name": 'Alex Barthet',
      "principal_image": "/assets/frontend/webinars/barthet.png",
      "video_url": "https://www.youtube.com/embed/PqxThzHfAXQ"
    },
    {
      id: 7,
      "title": 'How Do I Lien for Tenant Improvements?',
      "description": 'Learn about the mistakes people commit with change orders which cost them big time in this webinar hosted my Ariela Wagner, President, SunRay Construction Solutions and Alex Barthet Esq. Board Certified Lawyer and founder of The Lien zone.',
      "waiting_period": "In November",
      "webinar_day": new Date(15, 11, 2018),
      "start_time": '9:00 am',
      "end_time": '11:00 am',
      "status": "paid",
      "duration": "00:20",
      "webinar_image": "/assets/frontend/webinars/11th-webinar.jpg",
      "president_name": 'Ariela Wagner',
      "president_image": "/assets/frontend/webinars/ariela.png",
      "principal_name": 'Alex Barthet',
      "principal_image": "/assets/frontend/webinars/barthet.png",
      "video_url": "https://www.youtube.com/embed/PqxThzHfAXQ"
    },
    {
      id: 8,
      "title": 'I am Owed a Few Thousand Dollars. Is it Worth Hiring a Lawyer?',
      "description": 'Learn about the mistakes people commit with change orders which cost them big time in this webinar hosted my Ariela Wagner, President, SunRay Construction Solutions and Alex Barthet Esq. Board Certified Lawyer and founder of The Lien zone.',
      "waiting_period": "In December",
      "webinar_day": new Date(15, 12, 2018),
      "start_time": '9:00 am',
      "end_time": '11:00 am',
      "status": "paid",
      "duration": "00:20",
      "webinar_image": "/assets/frontend/webinars/12th-webinar.jpg",
      "president_name": 'Ariela Wagner',
      "president_image": "/assets/frontend/webinars/ariela.png",
      "principal_name": 'Alex Barthet',
      "principal_image": "/assets/frontend/webinars/barthet.png",
      "video_url": "https://www.youtube.com/embed/PqxThzHfAXQ"
    },
    {
      id: 9,
      "title": 'How to Get Paid after sending Notice of Non Payment?',
      "description": 'SunRay Construction Solutions and Alex Barthet Esq. Board Certified Lawyer and founder of The Lien zone.',
      "waiting_period": "In November",
      "webinar_day": new Date(15, 11, 2018),
      "start_time": '9:00 am',
      "end_time": '11:00 am',
      "status": "free",
      "duration": "00:23",
      "webinar_image": "/assets/frontend/webinars/open-uri.jpg",
      "president_name": 'Ariela Wagner',
      "president_image": "/assets/frontend/webinars/ariela.png",
      "principal_name": 'Alex Barthet',
      "principal_image": "/assets/frontend/webinars/barthet.png",
      "video_url": "https://www.youtube.com/embed/LvVJO3AKeJw"
    },
    {
      id: 10,
      "title": 'How do I get paid on a public project if there is no bond?',
      "description": 'Learn about the mistakes people commit with change orders which cost them big time in this webinar hosted my Ariela Wagner, President, SunRay Construction Solutions and Alex Barthet Esq. Board Certified Lawyer and founder of The Lien zone.',
      "waiting_period": "In December",
      "webinar_day": new Date(15, 12, 2018),
      "start_time": '9:00 am',
      "end_time": '11:00 am',
      "status": "free",
      "duration": "00:16",
      "webinar_image": "/assets/frontend/webinars/open-uri2.jpg",
      "president_name": 'Ariela Wagner',
      "president_image": "/assets/frontend/webinars/ariela.png",
      "principal_name": 'Alex Barthet',
      "principal_image": "/assets/frontend/webinars/barthet.png",
      "video_url": "https://www.youtube.com/embed/PqxThzHfAXQ"
    },
  ];

  getWebinars() {
    return this.webinars;
  }

}
